# Generated by Django 5.2.9 on 2026-02-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('iqraa_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('indian_address', models.TextField()),
                ('father_name', models.CharField(max_length=200)),
                ('father_iqraa_num', models.CharField(blank=True, max_length=50, null=True)),
                ('father_address', models.TextField(blank=True, help_text="Required if Father's Iqraa number is not provided", null=True)),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_iqraa_num', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_address', models.TextField(blank=True, help_text="Required if Mother's Iqraa number is not provided", null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('spouse_iqraa_num', models.CharField(blank=True, max_length=50, null=True)),
                ('spouse_address', models.TextField(blank=True, help_text="Required if Spouse's Iqraa number is not provided", null=True)),
                ('children', models.JSONField(blank=True, default=list, help_text='List of children with their details')),
                ('grandparents', models.TextField(blank=True, null=True)),
                ('tenure_from', models.DateField()),
                ('tenure_to', models.DateField()),
                ('iqraa_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('iqraa_department', models.CharField(blank=True, max_length=200, null=True)),
                ('iqraa_campus', models.CharField(blank=True, max_length=200, null=True)),
                ('memorable_experience', models.TextField(blank=True, null=True)),
                ('current_city', models.CharField(max_length=100)),
                ('professional_field', models.CharField(max_length=200)),
                ('alumni_activities_interest', models.CharField(max_length=200)),
                ('hear_about_us', models.CharField(blank=True, max_length=200, null=True)),
                ('hr_approved', models.BooleanField(default=False)),
                ('conform_register', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
