# Generated by Django 5.2.9 on 2026-02-27 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumniregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Alumni Registration', 'verbose_name_plural': 'Alumni Registrations'},
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='alumni_activities_interest',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Maybe', 'Maybe'), ('No', 'No')], default='Maybe', max_length=50, verbose_name='Interested in Alumni Activities'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='children',
            field=models.JSONField(blank=True, default=list, help_text='List of children with their details (name, age, iqraa, address)', verbose_name='Children'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='conform_register',
            field=models.BooleanField(default=False, verbose_name='Confirmed Registration'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='country',
            field=models.CharField(choices=[('Saudi Arabia', 'Saudi Arabia'), ('United Arab Emirates', 'United Arab Emirates'), ('Kuwait', 'Kuwait'), ('Qatar', 'Qatar'), ('Oman', 'Oman'), ('Bahrain', 'Bahrain')], max_length=100, verbose_name='Country of Residence'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='current_city',
            field=models.CharField(max_length=100, verbose_name='Current City'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='father_address',
            field=models.TextField(blank=True, help_text="Required if Father's Iqraa number is not provided", null=True, verbose_name="Father's Address"),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='father_iqraa_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Father's Iqraa Number"),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='father_name',
            field=models.CharField(max_length=200, verbose_name="Father's Name"),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='grandparents',
            field=models.TextField(blank=True, null=True, verbose_name='Grandparents Information'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='hear_about_us',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='How did you hear about us?'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='hr_approved',
            field=models.BooleanField(default=False, verbose_name='HR Approved'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='indian_address',
            field=models.TextField(verbose_name='Indian Address'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='iqraa_campus',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Iqraa Campus'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='iqraa_department',
            field=models.CharField(blank=True, choices=[('Administration', 'Administration'), ('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Other', 'Other')], max_length=200, null=True, verbose_name='Department at Iqraa'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='iqraa_designation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Designation at Iqraa'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='iqraa_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Iqraa Number'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='memorable_experience',
            field=models.TextField(blank=True, null=True, verbose_name='Memorable Experience at Iqraa'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='mother_address',
            field=models.TextField(blank=True, help_text="Required if Mother's Iqraa number is not provided", null=True, verbose_name="Mother's Address"),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='mother_iqraa_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Mother's Iqraa Number"),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='mother_name',
            field=models.CharField(max_length=200, verbose_name="Mother's Name"),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Phone number must be entered in format: '+999999999'. Up to 15 digits allowed.")], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='professional_field',
            field=models.CharField(max_length=200, verbose_name='Professional Field'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='spouse_address',
            field=models.TextField(blank=True, help_text="Required if Spouse's Iqraa number is not provided", null=True, verbose_name="Spouse's Address"),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='spouse_iqraa_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Spouse's Iqraa Number"),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Spouse Name'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='tenure_from',
            field=models.DateField(verbose_name='Tenure From'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='tenure_to',
            field=models.DateField(verbose_name='Tenure To'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='whatsapp_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="WhatsApp number must be entered in format: '+999999999'.")], verbose_name='WhatsApp Number'),
        ),
    ]
