# Generated by Django 5.2.9 on 2026-02-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_department_alter_alumniregistration_iqraa_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniregistration',
            name='grandparents',
        ),
    ]
