# Generated by Django 5.2.9 on 2026-02-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_alumniregistration_grandparents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniregistration',
            name='alumni_activities_interest',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Maybe', 'Maybe'), ('No', 'No')], default='Yes', max_length=50, verbose_name='Interested in Alumni Activities'),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='hear_about_us',
            field=models.CharField(blank=True, choices=[('social_media', 'Social Media'), ('twitter', 'Twitter'), ('friend', 'Friend or Family'), ('colleague', 'Colleague'), ('alumni_event', 'Alumni Event'), ('other', 'Other')], max_length=200, null=True, verbose_name='How did you hear about us?'),
        ),
    ]
