# Generated by Django 5.2.9 on 2026-03-08 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_alumniregistration_alumni_activities_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniregistration',
            name='father_pincode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Pincode must be exactly 6 digits.')], verbose_name="Father's Pincode"),
        ),
        migrations.AddField(
            model_name='alumniregistration',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='alumniregistration',
            name='mother_pincode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', message='Pincode must be exactly 6 digits.')], verbose_name="Mother's Pincode"),
        ),
        migrations.AlterField(
            model_name='alumniregistration',
            name='hear_about_us',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='How did you hear about us?'),
        ),
    ]
