# Generated by Django 5.2.9 on 2026-03-08 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alumniregistration_father_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniregistration',
            name='age',
            field=models.PositiveIntegerField(default=True, help_text='Age in years', validators=[django.core.validators.MinValueValidator(1, message='Age must be at least 1'), django.core.validators.MaxValueValidator(150, message='Age cannot exceed 150')], verbose_name='Age'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumniregistration',
            name='father_age',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Age in years', null=True, validators=[django.core.validators.MinValueValidator(1, message='Age must be at least 1'), django.core.validators.MaxValueValidator(150, message='Age cannot exceed 150')], verbose_name="Father's Age"),
        ),
        migrations.AddField(
            model_name='alumniregistration',
            name='mother_age',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Age in years', null=True, validators=[django.core.validators.MinValueValidator(1, message='Age must be at least 1'), django.core.validators.MaxValueValidator(150, message='Age cannot exceed 150')], verbose_name="Mother's Age"),
        ),
        migrations.AddField(
            model_name='alumniregistration',
            name='spouse_age',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Age in years', null=True, validators=[django.core.validators.MinValueValidator(1, message='Age must be at least 1'), django.core.validators.MaxValueValidator(150, message='Age cannot exceed 150')], verbose_name="Spouse's Age"),
        ),
    ]
