# Generated by Django 5.2.9 on 2026-04-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alumniregistration_age_alumniregistration_father_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniregistration',
            name='grandparents',
            field=models.JSONField(blank=True, default=list, help_text='List of grandparents with details', verbose_name='Grandparents Details'),
        ),
    ]
