# Generated by Django 5.2.9 on 2026-04-12 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alumniregistration_grandparents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniregistration',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age in years', null=True, validators=[django.core.validators.MinValueValidator(1, message='Age must be at least 1'), django.core.validators.MaxValueValidator(150, message='Age cannot exceed 150')], verbose_name='Age'),
        ),
    ]
